[package]
name = "test-shakmaty-pgn-to-uci"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
shakmaty = "0.29.1"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "my_benchmark"
harness = false
